// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  /// Android Firebase Configuration
  /// Isi sesuai credentials dari Firebase Console
  /// (firebase_options.dart akan diupdate setelah setup Firebase Console)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4eaapueL2_UZT_YEX7CltO2YX5fs0C0',
    appId: '1:214170465475:android:4ba859dcb395dbecdb5e76',
    messagingSenderId: '214170465475',
    projectId: 'ecopoin-unila',
    storageBucket: 'ecopoin-unila.firebasestorage.app',
  );
}
